default_stages: [commit]

default_install_hook_types: [pre-commit, commit-msg]

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude_types: [jupyter]
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        stages: [commit, commit-msg]
        args: [--check-filenames]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: [--drop-empty-cells, --keep-output]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: [--write] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.0.0-beta.2
    hooks:
      - id: eslint
        types: [file]
        args: [--fix]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - svelte
          - typescript
          - eslint-plugin-svelte
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
          - svelte-eslint-parser
