name: Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-14, windows-latest]
        python-version: ["3.10", "3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: |
          uv pip install cython setuptools --system

          python setup.py build_ext --inplace

          uv pip install -e .[test] --system

          # TODO remove next line installing ase from main branch when FrechetCellFilter is released
          uv pip install --upgrade 'ase@git+https://gitlab.com/ase/ase' --system

      - name: Run Tests
        run: pytest --capture=no --cov --cov-report=xml
        env:
          CHGNET_DEVICE: cpu

      - name: Codacy coverage reporter
        if: ${{ matrix.os == 'ubuntu-latest' && github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
